jdk:
- oraclejdk8
language: scala
sudo: required
scala:
- 2.12.8
cache:
 directories:
 - "$HOME/google-cloud-sdk/"
 - "$HOME/.ivy2/cache/"
 - "$HOME/.sbt/launchers/"
env:
 global:
 - GOOGLE_PROJECT=workbench-firestore
 - CLUSTER_NAME_PRD=standard-cluster-1
 - secure: cNcm26IOsmxqxnVFghdNYyulSls3OYd3DU9euliakHVLXfcY+rcYrOfjzYHmju+bWAHRJ/1DmMaVF7q/9zvGcEzBfn2qVbdfwS8pqjQBOk8I6ARdlyy+QHj8EA+pOVAWSGTcy2Ku3kcPF2kJbdhQwkB5+bMMXOMVsSBOq6dO8Ctsp9f3K4cdZ/Hj865wEjvWhaPW55gflktQIBuEuFF8dSaP6wohQyBvO6qrpDS+qjKsZxv/+qBxrLrwI3OhK9AGDfOC82zO+D0Rc/n0Gj/iu6v/QOW4eLzpA5mmWA18r3M36HGCT7NlZE2IkIPqcD+Kfi1t6zxg9JPy3Z599/YD3hvsJNPj/C7NvD+9sUychBYBFzVuXUDdynJ+x3+0UkvijMOSTDP1QsvJYrHOr1az+IJFaJSe+PYLCb+2qPhzCSskHNYf2QbGLMPQJ0h1QxPLcRkn9R+WmKCmoG7Xq6WHIliLGoiM/vBgp6uTet39yhiQKvf4tDAuAxX6+Go6byNLNICmQqw9DDlrgzV3Bl6M87r+TAEFkOuObCFBkIqDWGcPe0Yw+8pc3Ps3rk7dzt4vNrnRNFPvAvoKF8Yf9q0pEBIXIDZQM4H0/MFUOD00xgwGE+crexu9a14507RLXuq4204Sg1Q9m2PHSUOIq8C+fs+mHYveFRp0oEWa/elumCk=
before_install:
- openssl aes-256-cbc -K $encrypted_730b0c0ede05_key -iv $encrypted_730b0c0ede05_iv -in ccm-ci-cloud-build-credentials.tar.gz.enc -out ccm-ci-cloud-build-credentials.tar.gz -d
- if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash;
  fi
- gcloud version
- gcloud --quiet components update
- gcloud --quiet components update kubectl
- tar -xzf ccm-ci-cloud-build-credentials.tar.gz
- mkdir -p ${HOME}/.docker
- less ${GOOGLE_PROJECT}-ccm-ci.json|grep client_email
- sudo ls /var/lib/docker/image
- gcloud auth activate-service-account --key-file ${GOOGLE_PROJECT}-ccm-ci.json
- gcloud alpha auth configure-docker --quiet # add credHelper section to docker
- cat workbench-firestore-ccm-ci.json | docker login -u _json_key --password-stdin https://us.gcr.io
#- gcloud config set account ccm-ci@${GOOGLE_PROJECT}.iam.gserviceaccount.com -q
#- gcloud auth login -q
install:
- gcloud config set project ${GOOGLE_PROJECT}
- gcloud config set container/cluster $CLUSTER_NAME_PRD --quiet
- gcloud config set compute/zone us-central1-a
#- gcloud auth activate-service-account --key-file ${GOOGLE_PROJECT}-ccm-ci.json
- cat ~/.docker/config.json
- gcloud auth list -q
- sbt server/docker:publish
- deploy.sh
- export SBT_OPTS="-Dhost=130.211.211.97  -Dgrpc.port=80"
script:
- export COVERALLS_REPO_TOKEN=$coverall_token
- sbt clean coverage test coverageReport && sbt coverageAggregate
after_success:
- sbt coveralls
